### ISSUE TITLE
it doesn't work :-(

### ISSUE THREAD

**Issue by entuccio** [vmassuchetto/beets-ydl#6]
Hello,

-> installed python3 -m pip package OK
->beet ydl https://www.youtube.com/watch?v=OoMmK1q6pyw

----------------------
zsh$ beet ydl "https://www.youtube.com/watch?v=OoMmK1q6pyw&t=18s"
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/usr/local/lib/python3.7/site-packages/beets/ui/__init__.py", line 1253, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/local/lib/python3.7/site-packages/beetsplug/ydl.py", line 101, in ydl_func
    outer_class.youtubedl(lib, opts, arg)
  File "/usr/local/lib/python3.7/site-packages/beetsplug/ydl.py", line 153, in youtubedl
    y = YoutubeDL(youtubedl_config)
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 353, in __init__
    self._screen_file = [sys.stdout, sys.stderr][params.get('logtostderr', False)]
TypeError: get() takes from 1 to 2 positional arguments but 3 were given

---------------------

Wha I could do?

Thank you

**Comment by jmpohl** [comment]
Would be happy to help maintain if this repo is dead. Thanks!

**Comment by reagle** [comment]
@jmpohl it is dead, did you fork it?

**Comment by jmpohl** [comment]
@reagle Nope, not something I am too invested in anymore either unfortunately :\
